<?php
$title = $teamId . ' team players';
$this->headTitle($title);
?>

<h1><?php echo $this->escapeHtml($title); ?></h1>
<table class="table table-striped">
	<tr>
		<th>Code</th>
		<th>Full name</th>
		<th>Position</th>
		<th>&nbsp;</th>
	</tr>
<?php foreach ($players as $player) : ?>
<tr>
    <td><?php echo $this->escapeHtml($player->getId());?></td>
	<td><?php echo $this->escapeHtml($player->getFullname());?></td>
	<td><?php echo $this->escapeHtml($player->getPosition());?></td>
	<td><a href="/nflgames/players/profile/<?php echo $player->getId() ?>" class="btn btn-default btn-xs" role="button">See profile</a></td>
</tr>
 <?php endforeach; ?>
 </table>