<div id="wrapper">
	<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse"
				data-target=".navbar-ex1-collapse">
				<span class="sr-only">Toggle navigation</span> <span
					class="icon-bar"></span> <span class="icon-bar"></span> <span
					class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img
				src="<?php echo $this->basePath('img/nfl-logo.png') ?>"
				alt="NFL Games" /></a>
		</div>

		<div class="collapse navbar-collapse navbar-ex1-collapse">
			<ul id="active" class="nav navbar-nav side-nav">
			<?php $selected = true; ?>
			<?php foreach ($teams as $team) { ?>
				<li <?php if ($teamId == $team->getId()) echo 'class="selected"' ?>><a
					href="/nfl/games/dashboard?team_id=<?php echo $team->getId() ?>"><?php echo strtoupper($team->getCity()) . ' ' . strtoupper($team->getName()) ?></a></li>
			<?php $selected = false; ?>
			<?php } ?>
			</ul>
		</div>
	</nav>

	<div id="page-wrapper">
		<div class="row">
			<div class="col-lg-12">
				<h1>
					Team Dashboard <small>Statistics and more</small>
				</h1>
			</div>
		</div>
		<div class="alert alert-info alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span>&times;</span></button>
            Select your team on the left column and get deep insight information on its wins and losses within ZRay.
        </div>
		<div class="row">
			<div class="col-md-6">
				<div class="panel panel-primary" style="height:350px;">
					<div class="panel-heading">
						<h3 class="panel-title">
							<i class="fa fa-bar-chart-o"></i> Home Win
							<span class="pull-right"><a href="#" style="color: white;">Games played <span class="badge"><?php echo $homeGamesCount ?></span></a></span>
						</h3>
					</div>
					<div class="panel-body">
						<div id="chart1" style="height:300px;"></div>
					</div>
				</div>
			</div>

			<div class="col-md-6">
				<div class="panel panel-primary" style="height:350px;">
					<div class="panel-heading">
						<h3 class="panel-title">
							<i class="fa fa-bar-chart-o"></i> Away Win
							<span class="pull-right"><a href="#" style="color: white;">Games played <span class="badge"><?php echo $awayGamesCount ?></span></a></span>
						</h3>
					</div>
					<div class="panel-body">
						<div id="chart2" style="height:300px;"></div>
					</div>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-lg-12">
				<div class="panel panel-primary">
					<div class="panel-heading">
						<h3 class="panel-title">
							<i class="fa fa-th"></i> Players
						</h3>
					</div>
					<div class="panel-body">
						<table class="table table-striped table-condensed">
							<tr>
								<th>Code</th>
								<th>Full name</th>
								<th>Position</th>
								<th>Status</th>
								<th>&nbsp;</th>
							</tr>
<?php foreach ($players as $player) : ?>
<tr>
								<td><?php echo $this->escapeHtml($player->getId());?></td>
								<td><?php echo $this->escapeHtml($player->getFullname());?></td>
								<td><?php echo $this->escapeHtml($player->getPosition());?></td>
								<td><?php echo $this->escapeHtml($player->getStatus());?></td>
								<td><a
										href="<?php echo $player->getProfileUrl() ?>"
										class="btn btn-default btn-xs profile" role="button" target="_blank">View
										profile</a></td>
							</tr>
 <?php endforeach; ?>
 </table>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- /#wrapper -->
<!-- PBAFooter START -->
<div style="width: 100%; height: 50px; clear: both;">&nbsp;</div>
<div id="pbafooter" class="pbfooter">
	<div class="container">
		<p>&copy; 2005 - <?php echo date('Y') ?> by Zend Technologies Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
	</div>
</div>

<style>
.pbfooter {
	width: 100%;
	height: 50px;
	background-color: #F58723;
	color: white;
	top: 0;
	left: 0;
	z-index: 1200;
	padding-top: 15px;
}
</style>

<script type="text/javascript">
    $(document).ready(function () {
        // put the pbfooter on the bottom of the page
        var height = ($(document).height() - $("#pbafooter").height()) + "px";        
        $("#pbafooter").css("top", ($(document).height() - $("#pbafooter").height()) + "px");

        $.get('/nfl/games-api/games/home-win?team_id=<?php echo $teamId; ?>', function(response) {
     	   Morris.Donut({
        	  element: 'chart1',
        	  labelColor: "white",
            /*formatter: function(y) {
        	    return y + '%';
            },*/
        	  data: response.data
        	});
        });
       
        $.get('/nfl/games-api/games/away-win?team_id=<?php echo $teamId; ?>', function(response) {
            Morris.Donut({
          	  element: 'chart2',
              labelColor: "white",
              /*formatter: function(y) {
          	    return y + '%';
              },*/
          	  data: response.data
          	});
        })
    });
</script>
<!-- PBAFooter END -->